export const CARD_SIZES = {
  POSTER: {
    width: 229,
    height: 359,
    image_width: 229,
    image_height: 300,
  },
  FOCUSED_POSTER: {
    width: 252,
    height: 375,
    image_width: 252,
    image_height: 330,
  },
  CHANNEL: {
    width: 280,
    height: 136,
    image_height: 45,
  },
  MOVIE: {
    width: 403,
    height: 302,
    image_width: 403,
    image_height: 243,
  },
  FOCUSED_MOVIE: {
    width: 440,
    height: 330,
    image_width: 440,
    image_height: 266,
  },
  SINGLE_MOVIE: {
    image_width: 325,
    image_height: 485,
  },
};

export const MOVIE_ARRAY = [
  {
    image_src: "images/aftertherain.png",
    item_title: "After the Rain",
    margin_left: 0,
    margin_right: 12,
    margin_top: 10,
    margin_bottom: 10,
  },
  {
    image_src: "images/loveunexpected.png",
    item_title: "Love Unexpected",
    margin_left: 12,
    margin_right: 12,
    margin_top: 10,
    margin_bottom: 10,
  },
  {
    image_src: "images/thehaunting.png",
    item_title: "The Haunting",
    margin_left: 12,
    margin_right: 12,
    margin_top: 10,
    margin_bottom: 10,
  },
  {
    image_src: "images/leaveittothejoneses.png",
    item_title: "Leave it to the Joneses",
    margin_left: 12,
    margin_right: 12,
    margin_top: 10,
    margin_bottom: 10,
  },
  {
    image_src: "images/beyondthehorizon.png",
    item_title: "Beyond the Horizon",
    margin_left: 12,
    margin_right: 0,
    margin_top: 10,
    margin_bottom: 10,
  },
];

export const SERIES_ARRAY = [
  {
    image_src: "images/undone.png",
    item_title: "Undone",
    margin_left: 0,
    margin_right: 12,
    margin_top: 10,
    margin_bottom: 10,
  },
  {
    image_src: "images/modernfamily.png",
    item_title: "Modern Family",
    margin_left: 12,
    margin_right: 12,
    margin_top: 10,
    margin_bottom: 10,
  },
  {
    image_src: "images/livinwithyourself.png",
    item_title: "Livin' with yourself",
    margin_left: 12,
    margin_right: 12,
    margin_top: 10,
    margin_bottom: 10,
  },
  {
    image_src: "images/adventure.png",
    item_title: "Adventure",
    margin_left: 12,
    margin_right: 12,
    margin_top: 10,
    margin_bottom: 10,
  },
  {
    image_src: "images/explorers.png",
    item_title: "Explorers",
    margin_left: 12,
    margin_right: 0,
    margin_top: 10,
    margin_bottom: 10,
  },
];

export const CHANNEL_ARRAY = [
  {
    image_src: "images/Channel1.png",
    item_title: "Channel Name",
    margin_left: 16,
    margin_right: 16,
    margin_top: 69,
    margin_bottom: 8,
  },
  {
    image_src: "images/Channel2.png",
    item_title: "Channel Name",
    margin_left: 16,
    margin_right: 16,
    margin_top: 8,
    margin_bottom: 8,
  },
  {
    image_src: "images/Channel3.png",
    item_title: "Channel Name",
    margin_left: 16,
    margin_right: 16,
    margin_top: 8,
    margin_bottom: 8,
  },
  {
    image_src: "images/Channel4.png",
    item_title: "Channel Name",
    margin_left: 16,
    margin_right: 16,
    margin_top: 8,
    margin_bottom: 8,
  },
  {
    image_src: "images/Channel2.png",
    item_title: "Channel Name",
    margin_left: 16,
    margin_right: 16,
    margin_top: 8,
    margin_bottom: 0,
  },
];

export const VERTICAL_ARRAY = [
  {
    x: 50,
    y: 100,
    rail_title: "MOVIES",
    card_array: MOVIE_ARRAY,
  },
  {
    x: 50,
    y: 520,
    rail_title: "SERIES",
    card_array: SERIES_ARRAY,
  },
];

export const MOVIE_PAGE_ARRAY = [
  {
    image_src: "images/empireofthesun.png",
    item_title: "Empire Of The Sun",
    margin_left: 12,
    margin_right: 12,
    margin_top: 10,
    margin_bottom: 10,
    title: "Empire Of The Sun",
    description: `Empire of the Sun is a 1987 American epic coming-of-age war film directed by Steven Spielberg and written by Tom Stoppard, based on J. G. Ballard's semi- autobiographical 1984 novel of the same name.The film tells the story of Jamie "Jim" Graham(Christian Bale), a young boy who goes from living with his wealthy British family in Shanghai to becoming a prisoner of war in an internment camp operated by the Japanese during World War II.`,
    trailer_src: "images/eosbackground.png",
  },
  {
    image_src: "images/finalhours.png",
    item_title: "The Final Hours",
    margin_left: 12,
    margin_right: 12,
    margin_top: 10,
    margin_bottom: 10,
    title: "The Final Hours",
    description: `These Final Hours is a 2013 Australian sci-fi apocalyptic thriller film written and directed by Zak Hilditch and starring Nathan Phillips and Angourie Rice in her film debut. It was selected to be screened as part of the Directors' Fortnight section of the 2014 Cannes Film Festival.`,
    trailer_src: "images/fhbackground.jpg",
  },
  {
    image_src: "images/notimetodie.png",
    item_title: "No Time To Die",
    margin_left: 12,
    margin_right: 12,
    margin_top: 10,
    margin_bottom: 10,
    title: "No Time To Die",
    description: `No Time to Die is a 2021 spy thriller film and the twenty-fifth in the James Bond series, and the fifth and final to star Daniel Craig as fictional British MI6 agent James Bond. The plot follows Bond, who has left active service with MI6, and is recruited by the CIA to find a kidnapped scientist, which leads to a showdown with a powerful and vengeful adversary armed with a technology capable of killing millions. It was directed by Cary Joji Fukunaga from a screenplay he co-wrote with Neal Purvis, Robert Wade and Phoebe Waller-Bridge, based on a story conceived by Purvis, Wade and Fukunaga.`,
    trailer_src: "images/nttdbackground.jpg",
  },
  {
    image_src: "images/alienreclamation.png",
    item_title: "Alien Reclamation",
    margin_left: 12,
    margin_right: 12,
    margin_top: 10,
    margin_bottom: 10,
    title: "Alien Reclamation",
    description: `In the year 2120, the Earth is governed by five corporations: Prodigy, Weyland-Yutani, Lynch, Dynamic and Threshold. In this Corporate Era, cyborgs (humans with both biological and artificial parts) and synthetics (humanoid robots with artificial intelligence) exist alongside humans. But the game is changed when the wunderkind Founder and CEO of Prodigy Corporation unlocks a new technological advancement: hybrids (humanoid robots infused with human consciousness). `,
    trailer_src: "images/arbackground.jpg",
  },
  {
    image_src: "images/peopleadventure.png",
    item_title: "Adventure",
    margin_left: 12,
    margin_right: 12,
    margin_top: 10,
    margin_bottom: 10,
    title: "Adventure",
    description:
      "Boolean union variant background text vertical rectangle background horizontal. Boolean union variant background text vertical rectangle background horizontal. Pen export mask font image ellipse ",
    trailer_src: "images/pabackground.jpg",
  },
];

export const MOVIE_DETAILS = [
  {
    genre: "Drama",
    length: "98 minutes",
    movie_info: "US - 1987 - PG - IMDb: 7.7",
    movie_title: "Empire Of The Sun",
    movie_description: `Empire of the Sun is a 1987 American epic coming-of-age war film directed by Steven Spielberg and written by Tom Stoppard, based on J. G. Ballard's semi- autobiographical 1984 novel of the same name.The film tells the story of Jamie "Jim" Graham(Christian Bale), a young boy who goes from living with his wealthy British family in Shanghai to becoming a prisoner of war in an internment camp operated by the Japanese during World War II.`,
    director: "Enzo G. Castellari",
    cast: "Enzo G. Castellari, Enzo G. Castellari, Enzo G. Castellari, Enzo G. Castellari",
    image_src: "images/empireofthesun.png",
  },
  {
    genre: "Drama",
    length: "98 minutes",
    movie_info: "US - 1987 - PG - IMDb: 7.7",
    movie_title: "The Final Hours",
    movie_description: `These Final Hours is a 2013 Australian sci-fi apocalyptic thriller film written and directed by Zak Hilditch and starring Nathan Phillips and Angourie Rice in her film debut. It was selected to be screened as part of the Directors' Fortnight section of the 2014 Cannes Film Festival.`,
    director: "Enzo G. Castellari",
    cast: "Enzo G. Castellari, Enzo G. Castellari, Enzo G. Castellari, Enzo G. Castellari",
    image_src: "images/finalhours.png",
  },
  {
    genre: "Drama",
    length: "98 minutes",
    movie_info: "US - 1987 - PG - IMDb: 7.7",
    movie_title: "No Time To Die",
    movie_description: `No Time to Die is a 2021 spy thriller film and the twenty- fifth in the James Bond series, and the fifth and final to star Daniel Craig as fictional British MI6 agent James Bond.The plot follows Bond, who has left active service with MI6, and is recruited by the CIA to find a kidnapped scientist, which leads to a showdown with a powerful and vengeful adversary armed with a technology capable of killing millions.It was directed by Cary Joji Fukunaga from a screenplay he co - wrote with Neal Purvis, Robert Wade and Phoebe Waller - Bridge, based on a story conceived by Purvis, Wade and Fukunaga.`,
    director: "Enzo G. Castellari",
    cast: "Enzo G. Castellari, Enzo G. Castellari, Enzo G. Castellari, Enzo G. Castellari",
    image_src: "images/notimetodie.png",
  },
  {
    genre: "Drama",
    length: "98 minutes",
    movie_info: "US - 1987 - PG - IMDb: 7.7",
    movie_title: "Alien Reclamation",
    movie_description: `In the year 2120, the Earth is governed by five corporations: Prodigy, Weyland-Yutani, Lynch, Dynamic and Threshold. In this Corporate Era, cyborgs (humans with both biological and artificial parts) and synthetics (humanoid robots with artificial intelligence) exist alongside humans. But the game is changed when the wunderkind Founder and CEO of Prodigy Corporation unlocks a new technological advancement: hybrids (humanoid robots infused with human consciousness).`,
    director: "Enzo G. Castellari",
    cast: "Enzo G. Castellari, Enzo G. Castellari, Enzo G. Castellari, Enzo G. Castellari",
    image_src: "images/alienreclamation.png",
  },
  {
    genre: "Drama",
    length: "98 minutes",
    movie_info: "US - 1987 - PG - IMDb: 7.7",
    movie_title: "Adventure",
    movie_description: `Boolean union variant background text vertical rectangle background horizontal. Boolean union variant background text vertical rectangle background horizontal. Pen export mask font image ellipse`,
    director: "Enzo G. Castellari",
    cast: "Enzo G. Castellari, Enzo G. Castellari, Enzo G. Castellari, Enzo G. Castellari",
    image_src: "images/peopleadventure.png",
  },
];

export const ROUTES_INDEX = {
  home: 0,
  live: 1,
  movies: 2,
  settings: 3,
};
